/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaccinatiesRouteImport } from './routes/vaccinaties'
import { Route as ToegankelijkheidRouteImport } from './routes/toegankelijkheid'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BronnenRouteImport } from './routes/bronnen'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaccinatiesIndexRouteImport } from './routes/vaccinaties.index'
import { Route as VaccinatiesIdRouteImport } from './routes/vaccinaties.$id'

const VaccinatiesRoute = VaccinatiesRouteImport.update({
  id: '/vaccinaties',
  path: '/vaccinaties',
  getParentRoute: () => rootRouteImport,
} as any)
const ToegankelijkheidRoute = ToegankelijkheidRouteImport.update({
  id: '/toegankelijkheid',
  path: '/toegankelijkheid',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BronnenRoute = BronnenRouteImport.update({
  id: '/bronnen',
  path: '/bronnen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaccinatiesIndexRoute = VaccinatiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VaccinatiesRoute,
} as any)
const VaccinatiesIdRoute = VaccinatiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VaccinatiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bronnen': typeof BronnenRoute
  '/dashboard': typeof DashboardRoute
  '/toegankelijkheid': typeof ToegankelijkheidRoute
  '/vaccinaties': typeof VaccinatiesRouteWithChildren
  '/vaccinaties/$id': typeof VaccinatiesIdRoute
  '/vaccinaties/': typeof VaccinatiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bronnen': typeof BronnenRoute
  '/dashboard': typeof DashboardRoute
  '/toegankelijkheid': typeof ToegankelijkheidRoute
  '/vaccinaties/$id': typeof VaccinatiesIdRoute
  '/vaccinaties': typeof VaccinatiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bronnen': typeof BronnenRoute
  '/dashboard': typeof DashboardRoute
  '/toegankelijkheid': typeof ToegankelijkheidRoute
  '/vaccinaties': typeof VaccinatiesRouteWithChildren
  '/vaccinaties/$id': typeof VaccinatiesIdRoute
  '/vaccinaties/': typeof VaccinatiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bronnen'
    | '/dashboard'
    | '/toegankelijkheid'
    | '/vaccinaties'
    | '/vaccinaties/$id'
    | '/vaccinaties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bronnen'
    | '/dashboard'
    | '/toegankelijkheid'
    | '/vaccinaties/$id'
    | '/vaccinaties'
  id:
    | '__root__'
    | '/'
    | '/bronnen'
    | '/dashboard'
    | '/toegankelijkheid'
    | '/vaccinaties'
    | '/vaccinaties/$id'
    | '/vaccinaties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BronnenRoute: typeof BronnenRoute
  DashboardRoute: typeof DashboardRoute
  ToegankelijkheidRoute: typeof ToegankelijkheidRoute
  VaccinatiesRoute: typeof VaccinatiesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vaccinaties': {
      id: '/vaccinaties'
      path: '/vaccinaties'
      fullPath: '/vaccinaties'
      preLoaderRoute: typeof VaccinatiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toegankelijkheid': {
      id: '/toegankelijkheid'
      path: '/toegankelijkheid'
      fullPath: '/toegankelijkheid'
      preLoaderRoute: typeof ToegankelijkheidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bronnen': {
      id: '/bronnen'
      path: '/bronnen'
      fullPath: '/bronnen'
      preLoaderRoute: typeof BronnenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaccinaties/': {
      id: '/vaccinaties/'
      path: '/'
      fullPath: '/vaccinaties/'
      preLoaderRoute: typeof VaccinatiesIndexRouteImport
      parentRoute: typeof VaccinatiesRoute
    }
    '/vaccinaties/$id': {
      id: '/vaccinaties/$id'
      path: '/$id'
      fullPath: '/vaccinaties/$id'
      preLoaderRoute: typeof VaccinatiesIdRouteImport
      parentRoute: typeof VaccinatiesRoute
    }
  }
}

interface VaccinatiesRouteChildren {
  VaccinatiesIdRoute: typeof VaccinatiesIdRoute
  VaccinatiesIndexRoute: typeof VaccinatiesIndexRoute
}

const VaccinatiesRouteChildren: VaccinatiesRouteChildren = {
  VaccinatiesIdRoute: VaccinatiesIdRoute,
  VaccinatiesIndexRoute: VaccinatiesIndexRoute,
}

const VaccinatiesRouteWithChildren = VaccinatiesRoute._addFileChildren(
  VaccinatiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BronnenRoute: BronnenRoute,
  DashboardRoute: DashboardRoute,
  ToegankelijkheidRoute: ToegankelijkheidRoute,
  VaccinatiesRoute: VaccinatiesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
